### ISSUE TITLE
Code Release Date

### ISSUE THREAD

**Issue by CastleLiang** [IBM/RegionViT#1]
Thank you much for this interesting work! Can I ask when you will release the source code and the pretrain models?

**Comment by dc3ea9f** [comment]
Hi, I have reproduced RegionViT. You can follow up my [code](https://github.com/dc3ea9f/RegionViT)  for your research.

**Comment by chunfuchen** [comment]
Hi, the codes have been released. closed this issue. please open another issue if you encounter any other problems. Thanks.
